### ISSUE TITLE
Who is the target audience

### ISSUE THREAD

**Issue by tarsius** [chrisdone/emacs-magit-config#1]
Who is this intended for? Non-emacs users who want to use just Magit?

If so, it should probably provide shell commands like `magit status` or `magit diff --staged`. Something like this kinda exists at https://github.com/magit/magit.sh. Would you be interested in maintaining that and/or integrating it into this configuration?

**Comment by chrisdone** [comment]
> Who is this intended for? Non-emacs users who want to use just Magit?

Yep, a friend wanted a better Git UI but has no time or patience to learn Emacs, so this is a bundle that works out of the box. He can just run `emacs -Q -l init.el` and call that whatever is convenient and run it in some dir.

> If so, it should probably provide shell commands like `magit status` or `magit diff --staged`. Something like this kinda exists at https://github.com/magit/magit.sh. Would you be interested in maintaining that and/or integrating it into this configuration?

Not so much, I can't maintain bash stuff. This is just a one-off thing I made for friends in 5 mins from my [emacs-haskell-config](https://github.com/chrisdone/emacs-haskell-config). If someone wants to make a more official magit 'in a box', that'll be cool.

**Comment by tarsius** [comment]
Okay. Thanks for the information.
